#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="timecontrol"
PROG="/usr/bin/$CONF"
PIDFILE="/var/run/$CONF.pid"

cleanup() {
	$("$PROG" stop) >/dev/null 2>&1
}

start_service() {
	config_load "$CONF"
	local enabled
	config_get_bool enabled "config" "enable" "0"

	if [ $enabled -ne 1 ]; then
		$(/etc/init.d/"$CONF" stop) >/dev/null 2>&1
		return 1
	fi

	if [ -f "$PIDFILE" ]; then
		pid=$(cat "$PIDFILE" 2>/dev/null)
		if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
			rm -f "$PIDFILE" >/dev/null 2>&1
		else
			$("$PROG" flush) >/dev/null 2>&1
		fi
	fi

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_set_param pidfile "$PIDFILE"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	cleanup
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
